### ISSUE TITLE
Cannot overwrite/multitenant oauth tokens

### ISSUE THREAD

**Issue by erikh** [MaximeD/gost#34]
Currently, if you try to initialize gost and already have an API key for it (from a previous installation), it will not try to replace or add a new one, but instead fail and post the first gist as 'anonymous'.

Here's an example of what the official ruby gist does, and what I think is the ideal situation for me at least:
![screenshot 2014-12-26 08 56 54](https://cloud.githubusercontent.com/assets/18923/5558451/44ed371e-8cdd-11e4-9071-f2269079cf49.png)

I don't have time to contribute patches (sorry!) so I hope this bug report will be sufficient.

Thanks for the great program!

**Comment by MaximeD** [comment]
Hello @erikh this is updated to use timestamps if you already have a token for `gost`. Thanks again for reporting it.
